#!/bin/sh

. /etc/rc.d/init.d/functions

prog="docsaptwebapp"

UserDirectory=/home/vagrant
MainDirectory=/vagrant
ConfigDirectory=/etc/docs_apt/docs.conf

start(){
	echo -n $"Starting $prog: "
	daemon $UserDirectory/pyEnv/bin/docsaptwebapp --config=$ConfigDirectory &>> $MainDirectory/output.log 2>>$MainDirectory/server/server.log &
	retval=$?

	if [ 0 -eq $retval ] ; then
		echo "OK."
	else
		echo "ERROR."
	fi

	return $retval
}

stop(){
	echo -n $"Stopping $prog: "
	retval=0

	appid=$(ps aux | grep "$UserDirectory/pyEnv/bin/docsaptwebapp" | grep -v grep | awk '{print $2}')

	if [ -n "$appid" ] ; then
		sudo kill $appid
		echo "OK."
		retval=$?
	else
		echo "server is not running"
		retval=1
	fi

	return $retval
}

restart(){
	stop
	start
}

rh_status(){
	status $prog
	retval=$?
	return $retval
}

case "$1" in
	start)
		$1
		;;
	stop)
		$1
		;;
	status)
		rh_status
		;;
	restart)
		$1
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart}"
		exit 2
esac