"""registration date to Doctors

Revision ID: 3bf2ebc70e9
Revises: b38b44024c
Create Date: 2015-06-18 22:47:35.364496

"""

# revision identifiers, used by Alembic.
revision = '3bf2ebc70e9'
down_revision = 'b38b44024c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('registration_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'registration_date')
    ### end Alembic commands ###
