"""first migration

Revision ID: 4a29f97cf1e
Revises: 
Create Date: 2015-05-31 23:49:02.501129

"""

# revision identifiers, used by Alembic.
revision = '4a29f97cf1e'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
