"""doctors have maximum work hours per week

Revision ID: b38b44024c
Revises: 4a29f97cf1e
Create Date: 2015-06-06 16:00:47.501598

"""

# revision identifiers, used by Alembic.
revision = 'b38b44024c'
down_revision = '4a29f97cf1e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('work_hours', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'work_hours')
    ### end Alembic commands ###
